export const MOCK_PROPERTIES = [
    {
        id: '1',
        title: 'Modern Apartment in Windhoek Central',
        description: 'A stunning modern apartment located in the heart of Windhoek. Close to all amenities, shopping malls, and business districts.',
        price: 8500,
        address: '12 Independence Ave, Windhoek',
        city: 'Windhoek',
        bedrooms: 2,
        bathrooms: 1,
        size: 75,
        type: 'Apartment',
        images: [
            'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=400&auto=format&fit=crop',
        ],
        amenities: ['Air Conditioning', 'Security', 'Parking', 'WiFi'],
    },
    {
        id: '2',
        title: 'Spacious Family Home with Pool',
        description: 'Perfect for a large family. Features a large swimming pool, braai area, and spacious garden.',
        price: 18000,
        address: '45 Sam Nujoma Dr, Klein Windhoek',
        city: 'Windhoek',
        bedrooms: 4,
        bathrooms: 3,
        size: 250,
        type: 'House',
        images: [
            'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=400&auto=format&fit=crop',
        ],
        amenities: ['Pool', 'Braai Area', 'Garden', 'Double Garage'],
    },
    {
        id: '3',
        title: 'Cozy Studio near NUST',
        description: 'Ideal for students or young professionals. Walking distance to NUST.',
        price: 4500,
        address: 'Robert Mugabe Ave, Windhoek West',
        city: 'Windhoek',
        bedrooms: 1,
        bathrooms: 1,
        size: 35,
        type: 'Studio',
        images: [
            'https://images.unsplash.com/photo-1536349788264-1b816db3cc13?q=80&w=400&auto=format&fit=crop',
        ],
        amenities: ['Furnished', 'Fiber Internet', 'Walk to Campus'],
    },
    {
        id: '4',
        title: 'Luxury Penthouse with City View',
        description: 'Experience luxury living at its finest with panoramic views of Windhoek.',
        price: 25000,
        address: 'Trift St, Windhoek Central',
        city: 'Windhoek',
        bedrooms: 3,
        bathrooms: 3,
        size: 180,
        type: 'Penthouse',
        images: [
            'https://images.unsplash.com/photo-1512918580421-b2feee0b8508?q=80&w=400&auto=format&fit=crop',
        ],
        amenities: ['Jacuzzi', 'Concierge', 'Gym', 'Underground Parking'],
    },
    {
        id: '5',
        title: 'Charming Cottage in Olympia',
        description: 'A beautiful cottage with a private garden in the quiet Olympia neighborhood.',
        price: 9500,
        address: '8 Olympia St, Olympia',
        city: 'Windhoek',
        bedrooms: 2,
        bathrooms: 1,
        size: 85,
        type: 'House',
        images: [
            'https://images.unsplash.com/photo-1600596542815-2495db9a9d5e?q=80&w=400&auto=format&fit=crop',
        ],
        amenities: ['Garden', 'Pet Friendly', 'Parking'],
    },
    {
        id: '6',
        title: 'Executive Apartment in Eros',
        description: 'High-end executive apartment with modern finishes and 24/7 security.',
        price: 14000,
        address: '22 Eros Rd, Eros',
        city: 'Windhoek',
        bedrooms: 2,
        bathrooms: 2,
        size: 95,
        type: 'Apartment',
        images: [
            'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=400&auto=format&fit=crop',
        ],
        amenities: ['Security', 'Gym', 'Pool', 'Balcony'],
    },
    {
        id: '7',
        title: 'Budget-Friendly Bachelor Pad',
        description: 'Affordable living space for singles. All utilities included.',
        price: 3500,
        address: '15 Katutura Main Rd, Katutura',
        city: 'Windhoek',
        bedrooms: 1,
        bathrooms: 1,
        size: 28,
        type: 'Studio',
        images: [
            'https://images.unsplash.com/photo-1554995207-c18c203602cb?q=80&w=400&auto=format&fit=crop',
        ],
        amenities: ['Utilities Included', 'Furnished'],
    },
    {
        id: '8',
        title: 'Elegant Townhouse in Ludwigsdorf',
        description: 'Spacious townhouse in one of Windhoeks most prestigious areas.',
        price: 22000,
        address: '33 Ludwigsdorf St, Ludwigsdorf',
        city: 'Windhoek',
        bedrooms: 4,
        bathrooms: 3,
        size: 200,
        type: 'House',
        images: [
            'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=400&auto=format&fit=crop',
        ],
        amenities: ['Garden', 'Double Garage', 'Pool', 'Security'],
    },
    {
        id: '9',
        title: 'Modern Loft in Grove Mall Area',
        description: 'Trendy loft-style apartment near Grove Mall with open-plan living.',
        price: 11000,
        address: '5 Chasie St, Kleine Kuppe',
        city: 'Windhoek',
        bedrooms: 2,
        bathrooms: 1,
        size: 70,
        type: 'Apartment',
        images: [
            'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=400&auto=format&fit=crop',
        ],
        amenities: ['Open Plan', 'Parking', 'Close to Mall'],
    },
    {
        id: '10',
        title: 'Seaside Apartment in Swakopmund',
        description: 'Wake up to ocean views in this beautiful coastal apartment.',
        price: 12000,
        address: '88 Strand St, Swakopmund',
        city: 'Swakopmund',
        bedrooms: 2,
        bathrooms: 2,
        size: 90,
        type: 'Apartment',
        images: [
            'https://images.unsplash.com/photo-1515263487990-61b07816b324?q=80&w=400&auto=format&fit=crop',
        ],
        amenities: ['Ocean View', 'Balcony', 'Parking'],
    },
    {
        id: '11',
        title: 'Family Home in Walvis Bay',
        description: 'Comfortable family home close to the lagoon and town center.',
        price: 10000,
        address: '12 Lagoon Dr, Walvis Bay',
        city: 'Walvis Bay',
        bedrooms: 3,
        bathrooms: 2,
        size: 140,
        type: 'House',
        images: [
            'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?q=80&w=400&auto=format&fit=crop',
        ],
        amenities: ['Garden', 'Garage', 'Close to Beach'],
    },
    {
        id: '12',
        title: 'Upmarket Flat in Maerua Mall Area',
        description: 'Convenient location near Maerua Mall with modern amenities.',
        price: 9000,
        address: '7 Centaurus Rd, Eros',
        city: 'Windhoek',
        bedrooms: 2,
        bathrooms: 1,
        size: 65,
        type: 'Apartment',
        images: [
            'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?q=80&w=400&auto=format&fit=crop',
        ],
        amenities: ['Security', 'Parking', 'Close to Mall'],
    },
    {
        id: '13',
        title: 'Rustic Farmhouse in Okahandja',
        description: 'Escape the city with this beautiful farmhouse on 5 hectares.',
        price: 15000,
        address: 'Farm Otjikoto, Okahandja',
        city: 'Okahandja',
        bedrooms: 4,
        bathrooms: 2,
        size: 180,
        type: 'House',
        images: [
            'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?q=80&w=400&auto=format&fit=crop',
        ],
        amenities: ['Farm Living', 'Borehole', 'Pet Friendly'],
    },
    {
        id: '14',
        title: 'Student Flatlet near UNAM',
        description: 'Perfect for UNAM students. Secure and affordable.',
        price: 4000,
        address: '45 UNAM Dr, Pionierspark',
        city: 'Windhoek',
        bedrooms: 1,
        bathrooms: 1,
        size: 30,
        type: 'Studio',
        images: [
            'https://images.unsplash.com/photo-1493809842364-78817add7ffb?q=80&w=400&auto=format&fit=crop',
        ],
        amenities: ['Security', 'WiFi', 'Furnished'],
    },
    {
        id: '15',
        title: 'Penthouse Suite in Klein Windhoek',
        description: 'Top floor penthouse with stunning mountain views.',
        price: 28000,
        address: '99 Uhland St, Klein Windhoek',
        city: 'Windhoek',
        bedrooms: 3,
        bathrooms: 2,
        size: 160,
        type: 'Penthouse',
        images: [
            'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?q=80&w=400&auto=format&fit=crop',
        ],
        amenities: ['Mountain View', 'Rooftop', 'Elevator'],
    },
    {
        id: '16',
        title: 'Cozy 1-Bed in Hochland Park',
        description: 'Well-maintained unit in a quiet residential area.',
        price: 6500,
        address: '18 Hochland Rd, Hochland Park',
        city: 'Windhoek',
        bedrooms: 1,
        bathrooms: 1,
        size: 45,
        type: 'Apartment',
        images: [
            'https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?q=80&w=400&auto=format&fit=crop',
        ],
        amenities: ['Quiet Area', 'Parking', 'Garden'],
    },
    {
        id: '17',
        title: 'Beachfront Villa in Henties Bay',
        description: 'Luxurious beachfront property for the ultimate coastal lifestyle.',
        price: 20000,
        address: '1 Beach Rd, Henties Bay',
        city: 'Henties Bay',
        bedrooms: 4,
        bathrooms: 3,
        size: 220,
        type: 'House',
        images: [
            'https://images.unsplash.com/photo-1613490493576-7fde63acd811?q=80&w=400&auto=format&fit=crop',
        ],
        amenities: ['Beachfront', 'Pool', 'Braai Area'],
    },
    {
        id: '18',
        title: 'Compact Studio in Khomasdal',
        description: 'Affordable and clean studio for young professionals.',
        price: 3800,
        address: '55 Khomasdal Main Rd, Khomasdal',
        city: 'Windhoek',
        bedrooms: 1,
        bathrooms: 1,
        size: 32,
        type: 'Studio',
        images: [
            'https://images.unsplash.com/photo-1560185127-6a8c57f0e7b3?q=80&w=400&auto=format&fit=crop',
        ],
        amenities: ['Secure', 'Furnished'],
    },
    {
        id: '19',
        title: 'Duplex in Academia',
        description: 'Spacious duplex with private entrance and garden.',
        price: 13000,
        address: '8 Academia St, Academia',
        city: 'Windhoek',
        bedrooms: 3,
        bathrooms: 2,
        size: 130,
        type: 'House',
        images: [
            'https://images.unsplash.com/photo-1600573472592-401b489a3cdc?q=80&w=400&auto=format&fit=crop',
        ],
        amenities: ['Private Garden', 'Braai', 'Garage'],
    },
    {
        id: '20',
        title: 'Luxury Apartment in Ausspannplatz',
        description: 'Premium apartment with high-end finishes in central location.',
        price: 16000,
        address: '22 Ausspann Plaza, Ausspannplatz',
        city: 'Windhoek',
        bedrooms: 2,
        bathrooms: 2,
        size: 100,
        type: 'Apartment',
        images: [
            'https://images.unsplash.com/photo-1600585154526-990dced4db0d?q=80&w=400&auto=format&fit=crop',
        ],
        amenities: ['Gym', 'Pool', 'Concierge', 'Parking'],
    },
    {
        id: '21',
        title: 'Garden Flat in Pionierspark',
        description: 'Private garden flat with separate entrance.',
        price: 7000,
        address: '15 Pioneer Ave, Pionierspark',
        city: 'Windhoek',
        bedrooms: 1,
        bathrooms: 1,
        size: 50,
        type: 'Apartment',
        images: [
            'https://images.unsplash.com/photo-1600566752355-35a1b1e4d0b4?q=80&w=400&auto=format&fit=crop',
        ],
        amenities: ['Private Entrance', 'Garden', 'Parking'],
    },
    {
        id: '22',
        title: 'Executive House in Avis',
        description: 'Stunning executive home in exclusive Avis neighborhood.',
        price: 30000,
        address: '5 Avis Dam Rd, Avis',
        city: 'Windhoek',
        bedrooms: 5,
        bathrooms: 4,
        size: 350,
        type: 'House',
        images: [
            'https://images.unsplash.com/photo-1600047509358-9dc75507daeb?q=80&w=400&auto=format&fit=crop',
        ],
        amenities: ['Pool', 'Staff Quarters', 'Triple Garage', 'Security'],
    },
    {
        id: '23',
        title: 'Affordable 2-Bed in Okuryangava',
        description: 'Budget-friendly family accommodation in growing area.',
        price: 5500,
        address: '88 Main Rd, Okuryangava',
        city: 'Windhoek',
        bedrooms: 2,
        bathrooms: 1,
        size: 60,
        type: 'Apartment',
        images: [
            'https://images.unsplash.com/photo-1560185127-bfa1407e3f44?q=80&w=400&auto=format&fit=crop',
        ],
        amenities: ['Secure Complex', 'Playground'],
    },
    {
        id: '24',
        title: 'Modern Townhouse in Rocky Crest',
        description: 'Contemporary townhouse in popular Rocky Crest suburb.',
        price: 12500,
        address: '33 Rock St, Rocky Crest',
        city: 'Windhoek',
        bedrooms: 3,
        bathrooms: 2,
        size: 120,
        type: 'House',
        images: [
            'https://images.unsplash.com/photo-1600585154363-67eb9e2e2099?q=80&w=400&auto=format&fit=crop',
        ],
        amenities: ['Modern Kitchen', 'Patio', 'Garage', 'Security'],
    },
]
